<?php

return [
    'institutions' => [
        [
            'id' => 'bac',
            'name' => 'BAC',
            'logo' => 'welfare/img/mfls/partners/bac.webp',
            'info' => 'Foundation and law programmes aligned with professional pathways in legal and business studies.',
            'programmes' => [
                'FIL (Foundation in Law)',
                'FIB (Foundation in Business)',
                'UKT Law',
                'UKT Business',
                'University of London LLB (UOL)',
            ],
        ],
        [
            'id' => 'iact',
            'name' => 'IACT',
            'logo' => 'welfare/img/mfls/partners/iact.webp',
            'info' => 'Creative media programmes focused on digital communications, broadcasting and film.',
            'programmes' => [
                'Diploma Digital Media & Communications',
                'Diploma in Broadcasting & Film',
            ],
        ],
        [
            'id' => 'unimy',
            'name' => 'UNIMY',
            'logo' => 'welfare/img/mfls/partners/unimy.webp',
            'info' => 'Technology-focused foundation and diploma pathways in IT, cybersecurity, robotics and game development.',
            'programmes' => [
                'FCE',
                'Diploma in IT (Cybersecurity)',
                'Diploma in Robotics & Automation',
                'Diploma in Game Development',
            ],
        ],
        [
            'id' => 'veritas',
            'name' => 'Veritas University College',
            'logo' => 'welfare/img/mfls/partners/veritas.webp',
            'info' => 'Flexible ODL and conventional programmes in business, accounting and early childhood education.',
            'programmes' => [
                'FIA (ODL)',
                'Diploma Early Childhood (ODL)',
                'BBA (ODL)',
                'BAAF (Conventional)',
                'Bachelors in Early Childhood Education',
            ],
        ],
        [
            'id' => 'reliance',
            'name' => 'Reliance College',
            'logo' => 'welfare/img/mfls/partners/reliance.webp',
            'info' => 'Hospitality and business diploma programmes with industry-oriented training.',
            'programmes' => [
                'Diploma in Hotel Management',
                'Diploma in Business Management',
                'Diploma in Culinary Arts',
            ],
        ],
        [
            'id' => 'binary',
            'name' => 'Binary University',
            'logo' => 'welfare/img/mfls/partners/binary.webp',
            'info' => 'Business, tourism, accounting and administration programmes from certificate to honours degree level.',
            'programmes' => [
                'BA (Hons) Business Management',
                'Diploma in Tourism Management',
                'Diploma in Accounting',
                'Diploma in Business Administration',
                'Certificate in Business',
            ],
        ],
        [
            'id' => 'unitar',
            'name' => 'UNITAR',
            'logo' => 'welfare/img/mfls/partners/unitar.webp',
            'info' => 'Wide-ranging foundation, diploma and degree programmes across business, education, hospitality and logistics.',
            'programmes' => [
                'Foundation in Art',
                'Diploma in Early Childhood Education',
                'Diploma in Accounting',
                'Diploma in Human Resource Management',
                'Diploma in Business Administration',
                'Diploma in Logistics and Supply Chain Management',
                'Diploma in Hotel Management',
                'Bachelor Degree in Human Resource Management (Honours)',
                'Bachelor Degree in Business Management (Honours)',
                'Bachelor Degree in Education (TESL) with Honours',
                'Bachelor Degree in Hospitality Management (Honours)',
            ],
        ],
        [
            'id' => 'uoc',
            'name' => 'UOC',
            'logo' => 'welfare/img/mfls/partners/uoc.webp',
            'info' => 'Programmes spanning health sciences, design, business, pharmacy and mass communication.',
            'programmes' => [
                'Foundation in Science (Medicine/Pharmacy)',
                'Foundation in Allied Health Science',
                'Foundation in Arts',
                'Certificate in Business',
                'Certificate in Science',
                'Certificate in Information Technology',
                'Certificate in Visual Design',
                'Diploma in Healthcare',
                'Diploma in Nursing',
                'Bachelor of Counseling',
                'Diploma in Graphic Design',
                'Diploma in 3D Animation',
                'Diploma in Accounting',
                'Bachelor of Pharmacy',
                'Bachelor in Mass Communication',
                'Bachelor in Early Childhood Education',
                'Bachelor of Accounting and Finance',
            ],
        ],
        [
            'id' => 'mahsa',
            'name' => 'MAHSA University',
            'logo' => 'welfare/img/mfls/partners/mahsa.webp',
            'info' => 'Comprehensive pathways across health sciences, engineering, business, hospitality and professional degrees.',
            'programmes' => [
                'Foundation in Science',
                'Foundation in Business',
                'Diploma in Dental Technology',
                'Diploma in Environmental Health',
                'Diploma in Occupational and Safety',
                'Diploma in Medical Imaging (Radiography)',
                'Diploma in Paramedical Science',
                'Diploma in Beauty and Health',
                'Diploma in Mechanical Engineering',
                'Diploma in Civil Engineering',
                'Diploma in Quantity Surveying (Honours)',
                'Diploma in Architectural Technology',
                'Diploma in Business Administration',
                'Diploma in Human Resource Management',
                'Diploma in Marketing',
                'Diploma in Accounting',
                'Diploma in Hotel Management',
                'Diploma in Restaurant Management',
                'Diploma in Nursing',
                'Diploma in Physiotherapy',
                'Degree in Nursing',
                'Degree in Physiotherapy',
                'Degree in Radiography',
                'Degree in Environmental Health',
                'Degree in Business Administration',
                'Master in Business Administration',
                'Master in Hospital Management',
                'Master in Pharmacy',
                'Degree in Medicine (MBBS)',
                'Degree in Dentistry (DDS)',
                'Degree in Pharmacy',
            ],
        ],
        [
            'id' => 'sg-academy',
            'name' => 'SG Academy',
            'logo' => 'welfare/img/mfls/partners/sg-academy.webp',
            'info' => 'Industry-certified training programmes in drone operations, EV competency and artificial intelligence.',
            'programmes' => [
                'Drone Training (Certified by Civil Aviation)',
                'EV Competency Training (Certified by Autotronics EV Center)',
                'Artificial Intelligence Proficiency (Certified by SG AI Academy)',
            ],
        ],
    ],

    'faqs' => [
        [
            'question' => 'Can I apply to more than one programme?',
            'answer' => 'Yes, you may apply to more than one programme. However, you will only be awarded one scholarship at a single selected university.',
        ],
        [
            'question' => 'If I receive another scholarship, can I still accept the MUKMIN Scholarship?',
            'answer' => 'No. If you have already been awarded another scholarship, we ask that you do not also accept the MUKMIN Scholarship, so that we can extend the opportunity to other deserving candidates.',
        ],
        [
            'question' => 'Are there any obligations after receiving the scholarship?',
            'answer' => 'As a MFLS scholar, you will have certain obligations, but there is no bond attached to the scholarship. We do, however, encourage you to pay it forward by supporting the next generation of MFLS scholars and helping us nurture more leaders like you.',
        ],
        [
            'question' => 'Can I apply while waiting for my final results (Foundation, Diploma, or Degree)?',
            'answer' => 'Yes. We are happy to review your application based on your conditional results. Your final offer will be subject to confirmation of your final results.',
        ],
        [
            'question' => 'I am already studying at another university. Can I apply for the Education Fund?',
            'answer' => 'Our scholarships are available only for our participating universities. That said, MUKMIN and Fikrah provide limited zakat and social aid funding. If you require financial assistance as a student, you are welcome to apply for this support.',
        ],
        [
            'question' => 'Are there any hidden charges?',
            'answer' => 'There are no hidden charges. We do recommend that you fully understand the parameters of the scholarship including what it covers and for how long, before accepting it. The MUKMIN and Fikrah secretariat will provide counselling and guidance to help you make an informed decision before you accept.',
        ],
        [
            'question' => 'Does the scholarship provide a monthly allowance?',
            'answer' => 'Not all scholarships are the same, so we encourage you to understand the scope of your scholarship before accepting it. Some scholarships include an allowance, while many do not. In addition, MUKMIN offers social aid financing for special circumstances, which is reviewed on a case-by-case basis.',
        ],
        [
            'question' => 'What happens if my child does not perform well academically?',
            'answer' => 'Scholars are expected to maintain satisfactory academic progress throughout their studies. If a scholar experiences academic difficulty, the MUKMIN and Fikrah secretariat will work with the student to provide guidance and support. Continued funding may be subject to meeting the academic requirements set out in the scholarship agreement.',
        ],
        [
            'question' => 'Is accommodation provided?',
            'answer' => 'This depends on your specific scholarship. Please check your scholarship coverage carefully, as not all scholarships include accommodation.',
        ],
        [
            'question' => 'Are the programmes recognised?',
            'answer' => 'Yes. All of our partner universities and their programmes are recognised by the Malaysian Qualifications Agency (MQA).',
        ],
        [
            'question' => 'Can students continue to a higher qualification after graduation (for example, from Foundation to Degree)?',
            'answer' => 'Scholars can certainly continue if they meet the university academic and entrance requirements. With regards to the continuation of the scholarship, it depends on the parameters of the scholarship. We encourage you to speak with our counsellors to fully understand the scope of your scholarship and what further study it may support.',
        ],
        [
            'question' => 'How long does the selection process take?',
            'answer' => 'The selection process typically takes around two months from the time you apply.',
        ],
        [
            'question' => 'If I am unsuccessful, can I apply again?',
            'answer' => 'Yes. If your application is unsuccessful, you are welcome to apply again for the next academic calendar year.',
        ],
        [
            'question' => 'Can I work part-time while studying?',
            'answer' => 'Yes, you may work part-time, provided it does not affect your studies or your academic results.',
        ],
        [
            'question' => 'I don\'t know what course to choose. Can someone advise me?',
            'answer' => 'Yes. MUKMIN runs an outreach programme designed to answer questions from candidates and help guide you in choosing the right course. Please stay tuned in our social media for the MFLS Outreach Programme.',
        ],
    ],
];
